feat(sonarqube): adiciona etapa de build

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -50,3 +50,28 @@ jobs:
             echo >&2 "Valid commit message."
           fi
 
+  build:
+    runs-on: ubuntu-latest
+    needs: preflight
+    steps:
+      - uses: actions/checkout@v4
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          architecture: x64
+          cache: maven
+
+      - name: Build with Maven
+        working-directory: ./crud
+        run: |
+          mvn -B package -f pom.xml
+          if [ $? -ne 0 ]; then
+            echo "Build failed. Please check your changes and try again."
+            exit 1
+          fi
+
+      
+
