feat(sonarqube): adiciona regex para validar commit

diff --git a/.github/workflows/maven.yml b/.github/workflows/maven.yml
--- a/.github/workflows/maven.yml
+++ b/.github/workflows/maven.yml
@@ -23,3 +23,30 @@ jobs:
           SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
         with:
           projectBaseDir: ./crud
+
+  preflight:
+    runs-on: ubuntu-latest
+    steps:
+      - name: Checkout code
+        uses: actions/checkout@v4
+
+      - name: Set up JDK 17
+        uses: actions/setup-java@v3
+        with:
+          java-version: '17'
+          distribution: 'temurin'
+          architecture: x64
+          cache: maven
+
+      - name: Validate commit message
+        run: |
+          REGEX="^(Merge|Revert|(build|chore|ci|docs|feat|fix|perf|refactor|revert|style|test|Message)(\\(.+\\))?!?: .)"
+          COMMIT_MESSAGE=$(git log --format=%B -n 1 $GITHUB_SHA)
+          echo "Commit Message: ${COMMIT_MESSAGE}"
+          if ! [[ $COMMIT_MESSAGE =~ $REGEX ]]; then
+            echo >&2 "ERROR: Commit aborted for not following the Conventional Commit standard."
+            exit 1
+          else
+            echo >&2 "Valid commit message."
+          fi
+
